### ISSUE TITLE
app menu section does not scroll on mobile

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/gondor#101]
When the app menu and team members section is below Calendar. The window does not scroll over the app menu and team members section.

**Comment by 0xnmn** [comment]
Add loom recording or gif.

**Comment by samagragupta** [comment]
@hereisnaman 
![abc](https://user-images.githubusercontent.com/32234926/82732614-dc18f880-9d2b-11ea-90e7-e72f8a45eec4.gif)

**Comment by jugshaurya** [comment]
@hereisnaman, would like to work if @samagragupta not working.

**Comment by samagragupta** [comment]
@jugshaurya I am working on that.

**Comment by 0xnmn** [comment]
@samagragupta how are you trying to solve this issue?

**Comment by jugshaurya** [comment]
@samagragupta  @hereisnaman,I think simply adding a height of 100vh to scroll menu can solve this. I tried and it works

**Comment by 0xnmn** [comment]
> @samagragupta @hereisnaman,I think simply adding a height of 100vh to scroll menu can solve this. I tried and it works

How will 100vh work for desktop? Please share a gif.

**Comment by jugshaurya** [comment]
> > @samagragupta @hereisnaman, I think simply adding a height of 100vh to scroll menu can solve this. I tried and it works
> 
> How will 100vh work for desktop? Please share a gif.

@hereisnaman, sorry my bad: max-height: 100vh can solve this. here is how:

![a](https://user-images.githubusercontent.com/39825643/82782450-f9f47380-9e79-11ea-8d61-6dcb6a7ef007.gif)

**Comment by 0xnmn** [comment]
> > > @samagragupta @hereisnaman, I think simply adding a height of 100vh to scroll menu can solve this. I tried and it works
> > 
> > 
> > How will 100vh work for desktop? Please share a gif.
> 
> @hereisnaman, sorry my bad: max-height: 100vh can solve this. here is how:
> 
> ![a](https://user-images.githubusercontent.com/39825643/82782450-f9f47380-9e79-11ea-8d61-6dcb6a7ef007.gif)

Go ahead, create a PR.

**Comment by samagragupta** [comment]
@hereisnaman @jugshaurya From that we can scroll the team members section only. We cannot scroll the window.
I think we can also `wheelPropagation` true so that it can also scroll the window.
Should I make a PR @hereisnaman 
Like this:
![213](https://user-images.githubusercontent.com/32234926/82783378-f104a180-9e7b-11ea-95ee-a82e2e240902.gif)

**Comment by jugshaurya** [comment]
@samagragupta no I dont think scroll window is going to be a problem. try adding the main section again (just for testing). we can scroll the window. I don't think there is a problem with that.
![countr](https://user-images.githubusercontent.com/39825643/82784101-7a68a380-9e7d-11ea-8b93-75075baf9f21.png)

**Comment by 0xnmn** [comment]
@samagragupta @jugshaurya Lets discuss both the implementations in detail. You both raise the PR.

I think enabling wheel propagation will be better. I'll compare them locally once both the PRs are raised.

**Comment by jugshaurya** [comment]
@hereisnaman please review

**Comment by samagragupta** [comment]
> @samagragupta @jugshaurya Lets discuss both the implementations in detail. You both raise the PR.
> 
> I think enabling wheel propagation will be better. I'll compare them locally once both the PRs are raised.

Okay, I will create the PR with my implementation.
