### ISSUE TITLE
[Styles] Position of search icon in search bar of teammates

### ISSUE THREAD

**Issue by coderrsid** [coding-blocks/gondor#109]
## How it is
![image](https://user-images.githubusercontent.com/35633575/82736680-35dbeb80-9d49-11ea-8740-874c3b1d5dfd.png)

## How it should be 
![image](https://user-images.githubusercontent.com/35633575/82736706-5dcb4f00-9d49-11ea-8657-d330eb4c86c4.png)

**Comment by coderrsid** [comment]
Should i make the change in gogo-styles as it's using :after selector from there or add a class to the icon element?

**Comment by 0xnmn** [comment]
> Should i make the change in gogo-styles as it's using :after selector from there or add a class to the icon element?

no need to add extra class, just override the css in _custom.scss
