### ISSUE TITLE
[Styles] Wrong position of invalid email notification

### ISSUE THREAD

**Issue by coderrsid** [coding-blocks/gondor#111]
![image](https://user-images.githubusercontent.com/35633575/82736782-c7e3f400-9d49-11ea-9b7b-f3df1d46a36d.png)

**Comment by 0xnmn** [comment]
What is the issue with this?

**Comment by coderrsid** [comment]
The dialog is almost inside the input bar. Shouldn't be that below the bar atleast.

**Comment by coderrsid** [comment]
![image](https://user-images.githubusercontent.com/35633575/82736848-2e691200-9d4a-11ea-8926-33a6a755ce4d.png)

**Comment by coderrsid** [comment]
This looks better i guess
![image](https://user-images.githubusercontent.com/35633575/82736874-6708eb80-9d4a-11ea-82f5-22a9966a4aa5.png)

**Comment by 0xnmn** [comment]
It is fine to have it the current way. Theme reference: https://gogo-react.coloredstrategies.com/app/ui/forms/validations
