### ISSUE TITLE
[Migration] To generate slug for all the current events and change slug column to not null

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#113]
Add a migration which first generates and add slug for all the calendar events in the database and then change the column to not null.

Update:
Also set the slug column to be unique.

**Comment by kunal202** [comment]
I would  like to work on this issue

**Comment by 0xnmn** [comment]
> I would like to work on this issue

go ahead. I am assigning this to you.

**Comment by prathambatra** [comment]
@hereisnaman I am also looking into this.

**Comment by 0xnmn** [comment]
> @hereisnaman I am also looking into this.

Because there is possibly only one solution. I have assigned this issue to @kunal202 . If in 2 days there is no progress on this, you may take it up.

**Comment by prathambatra** [comment]
> > @hereisnaman I am also looking into this.
> 
> Because there is possibly only one solution. I have assigned this issue to @kunal202 . If in 2 days there is no progress on this, you may take it up.

ok i will wait.
