### ISSUE TITLE
[CalendarEvent ] Add auto_accept_requests.

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#114]
- [ ] Rename `is_open` to `is_requestable`. Write a migration to remove the old column and create a new one. Do the necessary changes in both api and app.
- [ ] Add new boolean column `auto_accept_requests` on `calendar_events`. Integrate it with create event and edit event flows. Add a check for `auto_accept_requests` to be only tru when `is_reqestable` is true.
- [ ] In calendar event request mutation, auto accept the request if it is marked on the event. Update the auth policy accordingly if required.

**Comment by jugshaurya** [comment]
@hereisnaman, I am working on this

**Comment by jugshaurya** [comment]
@hereisnaman , since we are removing the is_open now do we need to delete add_is_public_and_is_open migration because if someone run the migrations. It will add the is_open field as well right?

**Comment by jugshaurya** [comment]
@hereisnaman,  do I need to delete the is_public_is_open migration file now? Because if someone run the migrations the first time, it will add is_open column to DB which is a problem. as then is_open and is_requestable both exist. or does the migrations runs in some order ? so that first they are added and then renamed!

**Comment by 0xnmn** [comment]
> @hereisnaman, do I need to delete the is_public_is_open migration file now? Because if someone run the migrations the first time, it will add is_open column to DB which is a problem. as then is_open and is_requestable both exist. or does the migrations runs in some order ? so that first they are added and then renamed!

Migrations ones created are not deleted. 

What if all the people or even the production application which has already run that migration now on fresh pull doesn't get that already applied migration file.

Migrations are run in the order of their file name. It is my fault that I missed checking the file names of the migrations you added. As it is expected to for migrations to be generated using `sequelize migration:generate`

Please read through the Sequelize to avoid such mistakes in future.

**Comment by jugshaurya** [comment]
@hereisnaman , Ididnt actually added those migrations. It is my first time working for migration. But since people , atleast me have already run that migration and now we may have other developers coming up. How are we going to solve this wrong name files cases if they can't be deleted? Because they must be deleted! Right?

**Comment by joeedwin** [comment]
just rename them.?
Migrations run in alpahabetical order..........

**Comment by kunal202** [comment]
@jugshaurya  You can use `yarn sequelize db:migrate:undo` to undo the migrations, it will undo the changes

**Comment by 0xnmn** [comment]
> @hereisnaman , Ididnt actually added those migrations. It is my first time working for migration. But since people , atleast me have already run that migration and now we may have other developers coming up. How are we going to solve this wrong name files cases if they can't be deleted? Because they must be deleted! Right?

Yes in this very case, I'll rename the migration. We have to take care this does not happen in future. No worries.

**Comment by jugshaurya** [comment]
> > @hereisnaman , Ididnt actually added those migrations. It is my first time working for migration. But since people , atleast me have already run that migration and now we may have other developers coming up. How are we going to solve this wrong name files cases if they can't be deleted? Because they must be deleted! Right?
> 
> Yes in this very case, I'll rename the migration. We have to take care this does not happen in future. No worries.

@hereisnaman, I think both add_is_public and add_slug files are not generated with `sequelize migrate:create` as both file names don't have date identifier in the folder names both require changes.

Let me know when changes are done. Will work on this issue then. as I have to undo last migration changes and run the new ones.

**Comment by 0xnmn** [comment]
> > > @hereisnaman , Ididnt actually added those migrations. It is my first time working for migration. But since people , atleast me have already run that migration and now we may have other developers coming up. How are we going to solve this wrong name files cases if they can't be deleted? Because they must be deleted! Right?
> > 
> > 
> > Yes in this very case, I'll rename the migration. We have to take care this does not happen in future. No worries.
> 
> @hereisnaman, I think both add_is_public and add_slug files are not generated with `sequelize migrate:create` as both file names don't have date identifier in the folder names both require changes.
> 
> Let me know when changes are done. Will work on this issue then. as I have to undo last migration changes and run the new ones.

You can do it in this PR. Add the date part to the files name in the order they should be applied.

**Comment by jugshaurya** [comment]
@joeedwin @hereisnaman I was working on it!!

**Comment by 0xnmn** [comment]
> @joeedwin @hereisnaman I was working on it!!

I don't see any PRs.
