### ISSUE TITLE
[Event] Add a new page for /events/<id_or_slug>

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#115]
- [ ] Update Protected directive to accept a boolean argument `post_execution`. If the arg is true then check for the authorization after calling the resolver and pass the value returned by the resolver as `entity` while calling the authorization policy.
- [ ] Mark the root query field `event` as `protected` and pass `post_execution` as `true`.
- [ ] Update AuthPolicy to allow read by not logged in users on calendar event if the `is_public` for the event is true. Otherwise restrict the read access to Members and event organisers.
- [ ] Update `EntityResolver` to check if the model has a slug field and auto update the query to find 1 item based on if either the`args.id` matches the `id` or `args.slug` matches the `slug`. Also throw `UserInputError` if both id and slug are undefined.
- [ ] Update the root level query field `event` to have 2 optional args `id` and `slug`.
- [ ] Add a new page `/events/[event_id_or_slug].js`. On page open the `ViewEvent` modal and pass the url param as id and slug. Update the modal to accept both id and slug and pass it to the query.
- [ ] Do complete testing of the features for all the user roles and logged out view.

The PRs will be accessed based on code quality, maintaining proper naming conventions as followed in the project and the completeness of the task.

You should do extensive testing before submitting the PR to be merged. You can raise a PR and mark it was WIP if you need help or in between reviews.

**Comment by jugshaurya** [comment]
@hereisnaman on it. assign it to me

**Comment by 0xnmn** [comment]
> @hereisnaman on it. assign it to me

You can not claim all the issues at the same time. Please work on only 1 issue at once.

**Comment by faraazahmad** [comment]
@hereisnaman I'm working on it

**Comment by 0xnmn** [comment]
> @hereisnaman I'm working on it

Go ahead, I see this is your first issue. As this is issue needs knowledge of almost the whole code base, you can reach me on discord if need any help.

**Comment by prathambatra** [comment]
> @hereisnaman I'm working on it

we decided to work together @faraazahmad

**Comment by faraazahmad** [comment]
Yes

**Comment by prathambatra** [comment]
@hereisnaman we are working together.

**Comment by 0xnmn** [comment]
@faraazahmad @prathambatra 

Great. Try to solve this issue step by step. There are 7 tasks. Open a PR once the first 1 is done and then get it reviewed on each task completion.

**Comment by coderrsid** [comment]
Can i work on this?

**Comment by coderrsid** [comment]
@hereisnaman. Is there a condition through which i have to provide the 2 optional args id and slug? and like i didn't really get this point.. and this is the directory of root level query file you're referring to?
![image](https://user-images.githubusercontent.com/35633575/82759130-dc3af600-9e08-11ea-9157-52a96fa7a36f.png)

**Comment by prathambatra** [comment]
@hereisnaman can you tell me this? why are we passing post_execution? we can make an event visible only to related people also by changing auth policy and using protected directive. what is the need for an extra argument?
