### ISSUE TITLE
[Events] Add unique slug conflict failover

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#132]
The slug field for events is unique. It is generated based on the event title. So 2 events having the same title will have same slug. On creating the second event, the request will fail have because of the unique constraint.

Before creating an event, check how many events with the similar slug exists `LIKE '<slug>%'`. If count is non zero, append `-<count + 1>` to the new slug and create the event.

**Comment by prabalsingh24** [comment]
@hereisnaman `slug` field in the table should be unique. But it does not have `unique` constraint in the table.
[slug-field-migration](https://github.com/coding-blocks/gondor/blob/f923413671e869854611912268bdc868e28b2f4d/api/migrations/20200526035531-add_slug_to_calendar_events.js#L8) shouldn't this be having `unique: true` ?

**Comment by 0xnmn** [comment]
> @hereisnaman `slug` field in the table should be unique. But it does not have `unique` constraint in the table.
> [slug-field-migration](https://github.com/coding-blocks/gondor/blob/f923413671e869854611912268bdc868e28b2f4d/api/migrations/20200526035531-add_slug_to_calendar_events.js#L8) shouldn't this be having `unique: true` ?

Because at that time the slug was nullable. Here is it set to unique: https://github.com/coding-blocks/gondor/blob/f923413671e869854611912268bdc868e28b2f4d/api/migrations/20200603194408-add-slug-to-not-null.js

But apparently the model is not updated accordingly. Can you fix that?

**Comment by prabalsingh24** [comment]
Should i do this in a different PR or the in my current PR only?
Also this would require a different Migration file right?

**Comment by 0xnmn** [comment]
> Should i do this in a different PR or the in my current PR only?
> Also this would require a different Migration file right?

You can do in the same PR. As mentioned there is no missing parts in the db structure. The column was marked as unique once it was set to not null in the migration file linked. 

You just need to update the sequelize model accordingly.
