### ISSUE TITLE
[ZoomAccounts] Fix N+1 issue in availability field

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#18]
To improve the performance of the query by reducing the no. of separate db queries. Need to batch the availability status check queries in [zoomAccount.availability](https://github.com/coding-blocks/gondor/blob/master/api/graphql/query/ZoomAccount/availability.js). 

Problem: [N+1](https://engineering.shopify.com/blogs/engineering/solving-the-n-1-problem-for-graphql-through-batching)
Solution: [Dataloader](https://www.npmjs.com/package/dataloader)
Learn: https://www.youtube.com/watch?v=OQTnXNCDywA

**Comment by coderrsid** [comment]
Can i work on this @hereisnaman ?

**Comment by 0xnmn** [comment]
@coderrsid sure, I am assigning it to you. Let me know if you need any help.

**Comment by coderrsid** [comment]
Although it'll be a big implementation. Sure i'll see what i can do.

**Comment by coderrsid** [comment]
@hereisnaman How exactly the query is reaching N+1 issue. I am not able to quite find that!

![image](https://user-images.githubusercontent.com/35633575/82207946-4b57ac80-9928-11ea-9023-381577e1a5d3.png)

**Comment by 0xnmn** [comment]
@coderrsid 
For the query:
```graphql
query FetchZoomAccounts {
  ZoomAccounts(availableDuring: ...) {
    id
    availability(dateTimeRange: ...)
  }
}
```

The number of sql queries will be:
1 for finding the list of N zoom accounts.
N queries to find the availability of each of them.

**Comment by coderrsid** [comment]
Hey naman, should i wait for the another similar issue for CalendarInvite as he also added dataloader package, so i don't want that package version conflicts happen??

**Comment by 0xnmn** [comment]
> Hey naman, should i wait for the another similar issue for CalendarInvite as he also added dataloader package, so i don't want that package version conflicts happen??

That is a 1 line change, how hard will it be to resolve it even if that comes?
