### ISSUE TITLE
[404] Create a 404 page 

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#20]
Taking inspiration from: https://online.codingblocks.com/404 create default nextjs 404 page.

**Comment by gauthampkrishnan** [comment]
Sir do you want the exact design or just a simple page?

**Comment by 0xnmn** [comment]
@gauthampkrishnan mainly the graphic only. And also can add a heading saying '404'. May be some bg color or gradient. Doesn't have to be exactly like anything. 

Simply something good to look at.

**Comment by scortier** [comment]
@hereisnaman  Can i work on this issue??

**Comment by gauthampkrishnan** [comment]
@scortier  yes you can

**Comment by coderrsid** [comment]
I want to work on this issue!

**Comment by abhinavgup** [comment]
I want to work on this issue

**Comment by 0xnmn** [comment]
@gauthampkrishnan @scortier @coderrsid @abhinavgup I'll merge the one looking best.

**Comment by rahullli** [comment]
I want to work on this issue

**Comment by vandana1499** [comment]
@hereisnaman May I work on this issue?  We need to create graphics for 404 page, right ?

**Comment by RaghavK16** [comment]
I will work on this.

**Comment by isourav545** [comment]
I want to work on this issue

**Comment by 0xnmn** [comment]
The best and quick solutions will be selected. The issue is open to everyone.

**Comment by anktrj** [comment]
how to render this component with 404 occurs. little help

**Comment by 0xnmn** [comment]
> how to render this component with 404 occurs. little help

I'll let you explore the Next Js docs for that.

**Comment by prathambatra** [comment]
@hereisnaman you want that for all incorrect routes  404 page should be rendered right? this is what happens in online.codingblocks.com

**Comment by prathambatra** [comment]
@hereisnaman do you also need dashboard as shown in 404 page of https://online.codingblocks.com/404

**Comment by jugshaurya** [comment]
@hereisnaman, is this issue also closed from https://github.com/coding-blocks/gondor/pull/47?

**Comment by 0xnmn** [comment]
> @hereisnaman do you also need dashboard as shown in 404 page of https://online.codingblocks.com/404

No need to wrap with dashboard layout.

**Comment by 0xnmn** [comment]
> @hereisnaman, is this issue also closed from #47?

No this is a separate issue.

**Comment by prathambatra** [comment]
@hereisnaman review #58
