### ISSUE TITLE
[Readme] Getting started is not enough

### ISSUE THREAD

**Issue by nitesh585** [coding-blocks/gondor#21]
This single command is not enough for getting started. Too many things are missing in that such as how to install npm, yarn, and install dependencies via yarn.

Is there any bounty under BOSS, that can be added to this issue?

**Comment by 0xnmn** [comment]
@Niteshrocks have added bounty, you can update the read me.

**Comment by nitesh585** [comment]
Thanks :)

**Comment by nitesh585** [comment]
Thanks :)

**Comment by rajdeepj1363** [comment]
Added hyperlink to GraphQl documentation.

**Comment by 0xnmn** [comment]
@rajdeepj1363 your PR has been merged, awarded you 20 points, you can claim it.
