### ISSUE TITLE
Proper arrangement of username and image

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/gondor#27]
![Capture](https://user-images.githubusercontent.com/32234926/82050325-93cb5c00-96d5-11ea-8910-531a9f2f7427.JPG)
IN mobile view: Proper arrangement of username and image

**Comment by 0xnmn** [comment]
Assigned bounty.

**Comment by Aakansha99** [comment]
Can i work on this issue?

**Comment by samagragupta** [comment]
@Aakansha99 Sorry, I have already created the PR.

**Comment by 0xnmn** [comment]
The solution is to change the column width the [right section](https://github.com/coding-blocks/gondor/blob/master/app/components/Navbar/index.js#L50) for mobile devices.

**Comment by 0xnmn** [comment]
> Can i work on this issue?

Yes you can.
