### ISSUE TITLE
Side bar is not of full height

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/gondor#28]
![Capture](https://user-images.githubusercontent.com/32234926/82050673-2d930900-96d6-11ea-8986-d49b913d0ad0.JPG)

**Comment by 0xnmn** [comment]
Assigned Bounty

**Comment by kunal13053** [comment]
I want to work on this issue.

**Comment by 0xnmn** [comment]
@samagragupta do you want to work on this? Otherwise I'll assign it to @kunal13053

**Comment by samagragupta** [comment]
@hereisnaman I want to work on this.
