### ISSUE TITLE
Menu button not working

### ISSUE THREAD

**Issue by samagragupta** [coding-blocks/gondor#29]
Theme Reference: https://gogo-react.coloredstrategies.com/app/dashboards/default
![Capture](https://user-images.githubusercontent.com/32234926/82050957-9b3f3500-96d6-11ea-9828-aff351464d82.JPG)
In mobile view: Menu button not working

**Comment by 0xnmn** [comment]
Assigned Bounty

**Comment by harshu1470** [comment]
can I work on this?

**Comment by 0xnmn** [comment]
@harshu1470 go ahead

**Comment by PyAgni** [comment]
@hereisnaman Is this bug only in mobile view or in desktop view too? I'm facing same issue in desktop view too. Can you please confirm?

**Comment by 0xnmn** [comment]
> @hereisnaman Is this bug only in mobile view or in desktop view too? I'm facing same issue in desktop view too. Can you please confirm?

We don't have such need in desktop view, but its good to have.

**Comment by coderrsid** [comment]
@hereisnaman  What is the actual use of this menu button here, as i can't see any handler attached to it? Is it used to enable/disable the view of the Sidebar component ? or any other component?

**Comment by 0xnmn** [comment]
Menu button should switch between states of the sidebar. Right now There is no submenu, so only hide and show the main sidebar menu.
