### ISSUE TITLE
[App] Add ErrorLayout component and integrate it with createPage

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#31]
Add a default error layout component saying "There was some error" and an image, taking inspiration from [here](https://online.codingblocks.com/404).

Use the component as the default ErrorComponent in [createPage](https://github.com/coding-blocks/gondor/blob/master/app/utils/createPage.js#L19).

Also integrate it with the _app component to be rendered on an error getting caught.

**Comment by anktrj** [comment]
I like to take up on this issue.
What I have understood is I have to first create a component for default error like https://online.codingblocks.com/404 then integrate it to createPage and _app component.
Am I right?

**Comment by 0xnmn** [comment]
@ankiiitraj yes you are right, I am assigning this to you.

**Comment by prathambatra** [comment]
@hereisnaman I also want to work on this.

**Comment by chtushar** [comment]
@hereisnaman Sir I'm unable to install some packages since they are deprecated, what to do?
![Screenshot from 2020-05-15 22-18-28](https://user-images.githubusercontent.com/33191895/82076522-98a30680-96fb-11ea-9b67-6ac8201e11cd.png)

**Comment by chtushar** [comment]
@hereisnaman Also getting this error on running `yarn dev`

![Screenshot from 2020-05-15 22-39-47](https://user-images.githubusercontent.com/33191895/82078367-a908b080-96fe-11ea-92a5-85c75c4bcda6.png)

**Comment by prathambatra** [comment]
@hereisnaman please tell me this - If I am setting this locally do I also need to run oneauth locally or I can give account.codingblocks.com in oneauth URL?

**Comment by 0xnmn** [comment]
@prathambatra you can create a client application at account.codingblocks.com and use it locally too, though that way you can only test with 1 user. 

There is impersonation feature available too, I'll add wiki about it.

**Comment by prathambatra** [comment]
@hereisnaman thanks. I was thinking of setting a state variable when we catch an error and then based on it render the error component in _app. It seems so simple. Am I missing something?

**Comment by 0xnmn** [comment]
> @hereisnaman thanks. I was thinking of setting a state variable when we catch an error and then based on it render the error component in _app. It seems so simple. Am I missing something?

No that is perfect, name it `hasError`.

**Comment by jugshaurya** [comment]
I guess it is same as adding Error Boundary to the App

**Comment by jugshaurya** [comment]
@hereisnaman  is it?

**Comment by 0xnmn** [comment]
@jugshaurya yes, error boundaries exists at various places but nothing is shown there right now.

**Comment by jugshaurya** [comment]
@hereisnaman I am working on this

**Comment by jugshaurya** [comment]
@hereisnaman is it what you want or if want some modification.

![is](https://user-images.githubusercontent.com/39825643/82119388-ba53ca80-979b-11ea-8432-29166137adbd.png)

- Tell me should I style it more or something you want to add to it.

**Comment by 0xnmn** [comment]
> @hereisnaman is it what you want or if want some modification.
> 
> ![is](https://user-images.githubusercontent.com/39825643/82119388-ba53ca80-979b-11ea-8432-29166137adbd.png)
> 
>     * Tell me should I style it more or something you want to add to it.

This should work for https://github.com/coding-blocks/gondor/issues/20. 
For a common ErrorLayout we can have the image and text below it saying "There was some error".

**Comment by jugshaurya** [comment]
Yes, I have created an ErrorLayout component which is used in both _app.js and CreatePage.js.

Will be creating a PR soon just asking for the design. 
- I am going with the same image in the screenshot as it is already available and doing image and text below it saying "There was some error" as per your comment.

**Comment by jugshaurya** [comment]
@hereisnaman Please review

**Comment by prathambatra** [comment]
@hereisnaman please review #49

**Comment by prathambatra** [comment]
![Screenshot from 2020-05-16 21-02-44](https://user-images.githubusercontent.com/29707062/82124007-12012e80-97ba-11ea-9f5b-381cb20ea588.png)

**Comment by prathambatra** [comment]
@hereisnaman please review #50
