### ISSUE TITLE
[BaseConnection] fix edge.cursor mismatch.

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#32]
The cursor for each node generated by the [BaseConnection](https://github.com/coding-blocks/gondor/blob/master/api/graphql/base/ConnectionResolver.js#L37) does not match with the start and end cursors generated by [Sequelize Pagination](https://www.npmjs.com/package/sequelize-cursor-pagination).

Check the implementation of the package and replicate/fix the logic of generating cursor in the BaseConnection to match the start and end cursors.

**Comment by bharath-123** [comment]
Hey I would like to work on this. I am beginning work on this.

**Comment by bharath-123** [comment]
How can I go about reproducing this issue?

**Comment by 0xnmn** [comment]
For reproducing the issue, make the following query using the graphql playground at `localhost:3000/api/graphql

```graphql
users {
  edges {
    node {
      id
    }
    cursor
  }
  pageInfo {
    startCursor
    endCursor
  }
}
```

You will see that the `startCursor` won't be same at `edges[0].cursor` and `edges[<last_index].cursor` won't be same as `endCursor`.

**Comment by coderrsid** [comment]
![image](https://user-images.githubusercontent.com/35633575/82202821-18a9b600-9920-11ea-8f59-c0ee88eb7795.png)

**Comment by coderrsid** [comment]
I don't have oneauth local setup, i am using ONEAUTH_CLIENT_ID, ONEAUTH_CLIENT_SECRET by creating the instance by second method in my env file
![image](https://user-images.githubusercontent.com/35633575/82206777-79d48800-9926-11ea-8886-5be810a8b8a5.png)

**Comment by jugshaurya** [comment]
@hereisnaman, users are coming to be null even if I have seeded the users? can u tell me why?
should I pass some headers?

![c](https://user-images.githubusercontent.com/39825643/84283971-436edf00-ab59-11ea-8bd2-1862135bbaa8.png)

![e](https://user-images.githubusercontent.com/39825643/84284265-96e12d00-ab59-11ea-85cb-d565ff6cfbb9.png)


User table data: -
![d](https://user-images.githubusercontent.com/39825643/84284020-52ee2800-ab59-11ea-81fa-00e0e8d7c800.png)
 
Also working on this issue

**Comment by 0xnmn** [comment]
@jugshaurya try setting withCredentials as true in the gql playground settings.

**Comment by jugshaurya** [comment]
> @jugshaurya try setting withCredentials as true in the gql playground settings.

yes, that worked thanks. Working on the issue now
