### ISSUE TITLE
[App Menu] Display right sidebar on mobile devices below the content

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#33]
Currently the right sidebar is hidden on mobile devices. Make it appear below the content.

Desktop
![Screenshot 2020-05-15 at 8 35 47 PM](https://user-images.githubusercontent.com/22571395/82065400-af416180-96eb-11ea-83e7-73a04e9ebec7.png)

Mobile
![Screenshot 2020-05-15 at 8 36 47 PM](https://user-images.githubusercontent.com/22571395/82065513-d5670180-96eb-11ea-8ecb-612a58e0761e.png)

**Comment by samagragupta** [comment]
I want to work on this.

**Comment by sonalibhatia23** [comment]
@media(max-width:799px){
	#site-content>.container{
		display: flex;
    	flex-flow: column;
	}

	#site-content>.container>#sidebar-right{
		display: block !important;
    	order: 2;
	}
}

**Comment by 0xnmn** [comment]
@samagragupta I am assigning this to you.

**Comment by aggautam2628** [comment]
I want to work on this.
