### ISSUE TITLE
Default value for clientId and clientSecret is required 

### ISSUE THREAD

**Issue by rational-kunal** [coding-blocks/gondor#34]
Default value for `clientId` and `clientSecret` is required to able to authenticate locally

ref:
https://github.com/coding-blocks/gondor/blob/2e92a1a02bf04c84fd1254793c8e339aef78e039/api/config/index.js#L7-L8

**Comment by 0xnmn** [comment]
Please follow the guidelines [here](https://github.com/coding-blocks/gondor#setting-up-oneauth) to setup oneauth locally and get the client id and secret.
