### ISSUE TITLE
[Event Types] Map event type with its name

### ISSUE THREAD

**Issue by joeedwin** [coding-blocks/gondor#39]
Create a event type - name map [here](https://github.com/coding-blocks/gondor/blob/master/app/components/ColorsList/index.js). Treat the `name` as type and render the actual name rather.

example:
```javascript
{
  OfflineClass: 'Offline Class',
  OnlineClass: 'Online Class',
}
```
![image](https://user-images.githubusercontent.com/26297616/82082686-12d88880-9706-11ea-8ddf-1ccd19beabf3.png)

**Comment by RutujaD182** [comment]
I have started to work on this issue.

**Comment by joeedwin** [comment]
I am already working
