### ISSUE TITLE
Hide Navbar and Sidebar based on query params

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#56]
In the Dashboard Layout, access the query params and hide Navbar and sidebar if `embed` query param exists.

**Comment by jugshaurya** [comment]
@hereisnaman I am working on this, assign it to me

**Comment by prathambatra** [comment]
@hereisnaman I also want to work on this.

**Comment by jugshaurya** [comment]
@hereisnaman, does hide means simply don't display like - 
![hide](https://user-images.githubusercontent.com/39825643/82155873-7d6bfe80-9895-11ea-8fe9-ed4d845fefb6.png)

or you want something else? can you please specify what does hide means? does this means simply not rendering these components or should I change some styles as well?

**Comment by jugshaurya** [comment]
or you want something like this.

![wanted](https://user-images.githubusercontent.com/39825643/82156236-a5f4f800-9897-11ea-93a9-71dac5c4dc49.png)

**Comment by 0xnmn** [comment]
@jugshaurya Simply hide the components and for '.dashboard-layout main' set margin 0 and padding: 20px!important;

**Comment by jugshaurya** [comment]
@hereisnaman,  do you want some name changes? 
![hide](https://user-images.githubusercontent.com/39825643/82156966-35040f00-989c-11ea-8416-ef270ce25022.png)

**Comment by 0xnmn** [comment]
> @hereisnaman, do you want some name changes?
> ![hide](https://user-images.githubusercontent.com/39825643/82156901-c921a680-989b-11ea-8687-c844a3f7aaf0.png)

Checkout [classnames](https://www.npmjs.com/package/classnames) library. Use it instead.

Also pass class name, no inline css.

**Comment by jugshaurya** [comment]
@hereisnaman, now - 
![hide](https://user-images.githubusercontent.com/39825643/82157240-dd66a300-989d-11ea-9660-4086c5af765b.png)

![hide1](https://user-images.githubusercontent.com/39825643/82157308-4a7a3880-989e-11ea-9dfc-a264e20377ae.png)

output-
![output](https://user-images.githubusercontent.com/39825643/82157319-67167080-989e-11ea-8fb2-7d4b3df83a50.png)

**Comment by jugshaurya** [comment]
@hereisnaman, is this the problem? for this URL http://localhost:3000/me/calendar?embed=

Navbar and sidebar will not hide as empty strings typecasts to false.

**Comment by 0xnmn** [comment]
> @hereisnaman, is this the problem? for this URL http://localhost:3000/me/calendar?embed=
> 
> Navbar and sidebar will not hide as empty strings typecasts to false.

Check only for the existence of key.

**Comment by jugshaurya** [comment]
> > @hereisnaman, is this the problem? for this URL http://localhost:3000/me/calendar?embed=
> > Navbar and sidebar will not hide as empty strings typecasts to false.
> 
> Check only for the existence of key.

- using hasOwnProperty() 
and classNames styling is fine?

**Comment by 0xnmn** [comment]
> > > @hereisnaman, is this the problem? for this URL http://localhost:3000/me/calendar?embed=
> > > Navbar and sidebar will not hide as empty strings typecasts to false.
> > 
> > 
> > Check only for the existence of key.
> 
>     * using hasOwnProperty()
>       and classNames styling is fine?

I'll review the final PR.

**Comment by jugshaurya** [comment]
@hereisnaman, close this issue, solved through https://github.com/coding-blocks/gondor/pull/61
