### ISSUE TITLE
[Events] Add is_public and is_open columns to calendar event.

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#57]
1. Write a migration to add `is_public` and `is_open` boolean columns to `calendar_events` table with default value as `false`. 
2. Update the sequelize model accordingly
3. Update CalendarEvent graphql type
4. Update the AuthorizationPolicy to allow update of the columns to organizer and admins and allow read to everyone.
5. Update CalendarEventCreate and CalendarEventUpdate mutations to support the new columns
6. Integrate the new columns in the create, view and edit event modals. In the create and edit modals have them as checkbox fields at the bottom named 'Public' and 'Open'. In the view modal have them as Badges of primary color at the bottom.
7. Update the CalendarEventRequest mutation to allow creating an invite request only if `is_open` is true for the event.
8. In the view event modal show request invite button only when `is_open` for the event is true.

Please maintain the code quality and naming conventions.

**Comment by joeedwin** [comment]
I will work on this

**Comment by prabalsingh24** [comment]
Can I work on this too?

**Comment by joeedwin** [comment]
I am working on this

**Comment by 0xnmn** [comment]
> Can I work on this too?

Yes you can, first PR with best code quality wins

**Comment by coderrsid** [comment]
@hereisnaman Should i use the badges from react-strap in the view event modal and what should be the type of badge when the it's false?

**Comment by coderrsid** [comment]
@hereisnaman 
1. Don't we have to update the attributes in API/services/CalendarEvent/Form? 
2. Also for the fragments, attribute is_open and is_public should be added to EventFragment GraphQL?

**Comment by 0xnmn** [comment]
@coderrsid 

1. That is how you update the createEvent and editEvent modals.
2. Yes you can add them in the fragment,
