### ISSUE TITLE
Graphql schema build removes spaces in file paths

### ISSUE THREAD

**Issue by coderrsid** [coding-blocks/gondor#62]
![](https://cdn.discordapp.com/attachments/711240540540239913/711557760214368296/unknown.png)

**Comment by jugshaurya** [comment]
@hereisnaman, i am trying this one. Isn't this problem get solved also using String.raw()?

**Comment by 0xnmn** [comment]
> @hereisnaman, i am trying this one. Isn't this problem get solved also using String.raw()?

no

**Comment by jugshaurya** [comment]
@hereisnaman, This one should work.
![r](https://user-images.githubusercontent.com/39825643/82364333-c7d3b380-9a2c-11ea-956b-834a87cf6fb7.png)

**Code Change:-**
![r1](https://user-images.githubusercontent.com/39825643/82364506-fea9c980-9a2c-11ea-8531-a0169f2e614e.png)

**testing:**
![r2](https://user-images.githubusercontent.com/39825643/82364898-88f22d80-9a2d-11ea-94c2-66659d1f8e99.png)

**Comment by 0xnmn** [comment]
@jugshaurya this needs to be solved by warping the dir name with space inside quotes.

**Comment by jugshaurya** [comment]
@hereisnaman, you meant like `'/Users/"BOSS 2022"/gondor'` this?

**Comment by 0xnmn** [comment]
yes

**Comment by jugshaurya** [comment]
@hereisnaman, may sound silly!😊 but for that:
1. split the pathString by "/"
2. then map over the array (val) => split val by space and if length>2 return val wrapped in quotes else return val;
3. join the array.
Complexity : (#number of `/` )
correct?

![r3](https://user-images.githubusercontent.com/39825643/82367159-fce20500-9a30-11ea-9987-684f14e3eb5e.png)

**Comment by 0xnmn** [comment]
> @hereisnaman, may sound silly!😊 but for that:
> 
>     1. split the pathString by "/"
> 
>     2. then map over the array (val) => split val by space and if length>2 return val wrapped in quotes else return val;
> 
>     3. join the array.
>        Complexity : (#number of `/` )
>        correct?
> 
> 
> ![r3](https://user-images.githubusercontent.com/39825643/82367159-fce20500-9a30-11ea-9987-684f14e3eb5e.png)

Not every new line of the code can be reviewed. Please explore the solution, extensively test it and then raise the PR. The final PR shall be reviewed.

**Comment by coderrsid** [comment]
@hereisnaman What is the actual catch and explaination of this issue? I'd like to fix this so no one else go through this like me..

**Comment by 0xnmn** [comment]
@jugshaurya solutions seems good. Can you create a PR?

**Comment by jugshaurya** [comment]
@hereisnaman Working on testing it. code already written
