### ISSUE TITLE
Truncate Event Title in View Event Modal

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#64]
Trumcate the event name  and add title attribute to the heading element with the value of event name. 
![Screenshot 2020-05-18 at 1 39 49 AM](https://user-images.githubusercontent.com/22571395/82158955-bcf01600-98a8-11ea-8528-f0e937470443.png)

**Comment by jugshaurya** [comment]
@hereisnaman, assign it to me

Also forex to Hawaii House Party, what should be the truncate value?

**Comment by 0xnmn** [comment]
> @hereisnaman, assign it to me
> 
> Also forex to Hawaii House Party, what should be the truncate value?

Hint: use bootstrap class for that.

**Comment by jugshaurya** [comment]
@hereisnaman, how can I get the authorization to create events.
whenever I am adding a new event. I am getting this. Although I am **not** able to invite users and add Zoom account.

![authoration-error](https://user-images.githubusercontent.com/39825643/82219103-7519cf00-993a-11ea-80fd-7732437540be.png)

**Comment by 0xnmn** [comment]
> @hereisnaman, how can I get the authorization to create events.
> whenever I am adding a new event. I am getting this. Although I am **not** able to invite users and add Zoom account.
> 
> ![authoration-error](https://user-images.githubusercontent.com/39825643/82219103-7519cf00-993a-11ea-80fd-7732437540be.png)

Study the AuthorizationPolicy in the application.

**Comment by jugshaurya** [comment]
@hereisnaman, I saw the Authorization Policy in Readme and created a client and saved id and secret in .env file, seed the DB with users data and since I used those ids and secret, it always logged me in as Default user. since I am also working at the impersonate feature. can you tell me **what should I put in place of username to update the role?**

![Screenshot from 2020-05-18 21-08-38](https://user-images.githubusercontent.com/39825643/82232729-a00d1e80-994c-11ea-9f1f-e70a6eefc74b.png)

**Comment by 0xnmn** [comment]
> @hereisnaman, I saw the Authorization Policy in Readme and created a client and saved id and secret in .env file, seed the DB with users data and since I used those ids and secret, it always logged me in as Default user. since I am also working at the impersonate feature. can you tell me **what should I put in place of username to update the role?**
> 
> ![Screenshot from 2020-05-18 21-08-38](https://user-images.githubusercontent.com/39825643/82232729-a00d1e80-994c-11ea-9f1f-e70a6eefc74b.png)

Paste your account username there. 

Also I was talking about the AuthorizationPolicy [here](https://github.com/coding-blocks/gondor/blob/master/api/services/AuthorizationPolicy/index.js)

**Comment by jugshaurya** [comment]
@hereisnaman, is this what you want?

![Screenshot from 2020-05-18 22-32-53](https://user-images.githubusercontent.com/39825643/82240269-bf5d7900-9957-11ea-8cd5-5cd8c63d4eb3.png)

**Comment by 0xnmn** [comment]
@jugshaurya is the action items including edit delete and the status be on the next line, it defeats the purpose of truncating.

**Comment by jugshaurya** [comment]
> @jugshaurya is the action items including edit delete and the status be on the next line, it defeats the purpose of truncating.

ok, so you want the title, edit-btn, delete-btn, and status(accepted or declined) on the same line.
don't you think it will get suffocating?

**Comment by jugshaurya** [comment]
@hereisnaman, you mean this 
![Screenshot from 2020-05-18 23-37-46](https://user-images.githubusercontent.com/39825643/82245516-b1f8bc80-9960-11ea-8474-54abbad2e42a.png)
?

**Comment by jugshaurya** [comment]
@hereisnaman Please review
