### ISSUE TITLE
Hide Attendees Label if no Attendees Present in View Event Modal

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#65]
Hide the attendees text in view event modal if the attendees array is empty.

![Screenshot 2020-05-18 at 1 39 49 AM](https://user-images.githubusercontent.com/22571395/82158987-f3c62c00-98a8-11ea-95f9-018827b02768.png)

**Comment by prathambatra** [comment]
I will work on this.

**Comment by coderrsid** [comment]
@hereisnaman , i got this error while adding an event to any date while testing 
![image](https://user-images.githubusercontent.com/35633575/82186355-5995d080-9908-11ea-8a98-a909ca024bf9.png)

Can i just add the PR for you to test it?

**Comment by 0xnmn** [comment]
> @hereisnaman , i got this error while adding an event to any date while testing
> ![image](https://user-images.githubusercontent.com/35633575/82186355-5995d080-9908-11ea-8a98-a909ca024bf9.png)
> 
> Can i just add the PR for you to test it?

Please study the authorization policy in the problem to fix this.
