### ISSUE TITLE
Build in Windows fails as it expects hexadecimal after "\u"

### ISSUE THREAD

**Issue by joeedwin** [coding-blocks/gondor#68]
As it is in filepath build should happen

**Screenshots**

![image](https://user-images.githubusercontent.com/26297616/82222775-6550b980-993f-11ea-9ad9-35a81a3cefe1.png)
![image](https://user-images.githubusercontent.com/26297616/82222999-aba61880-993f-11ea-975b-1601b78040a2.png)

Hint - "the path string has to be RAW and not un-escaped. Or you'll have to serialise it some other way."

i will not work

**Comment by jugshaurya** [comment]
@hereisnaman, I got its solution. Do I have to change all the template strings that are path in the whole project? or just the place where `\u` in windows us coming up?

**Comment by jugshaurya** [comment]
I will make a PR after the changes.

**Comment by 0xnmn** [comment]
> @hereisnaman, I got its solution. Do I have to change all the template strings that are path in the whole project? or just the place where `\u` in windows us coming up?

Depends on how are going to serialize it. What is your solution?

**Comment by jugshaurya** [comment]
using the String.raw(). [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw)

**Comment by jugshaurya** [comment]
String.raw\`/home/shaurya/dev/git_repos/gondor/api/graphql/query/user.js\`

**Comment by 0xnmn** [comment]
> String.raw`/home/shaurya/dev/git_repos/gondor/api/graphql/query/user.js`

Perfect, wrap all the paths for resolvers, mutations and directives too. Please do proper testing in windows environment.

**Comment by jugshaurya** [comment]
> > String.raw`/home/shaurya/dev/git_repos/gondor/api/graphql/query/user.js`
> 
> Perfect, wrap all the paths for resolvers, mutations and directives too. Please do proper testing in windows environment.

windows terminal? I have a Linux one 😊.  Any ideas how can I get windows terminal just for this task?  I am not on windows :)

**Comment by jugshaurya** [comment]
I can update the paths but testing can be done by @joeedwin, i guess.

**Comment by 0xnmn** [comment]
> > > String.raw`/home/shaurya/dev/git_repos/gondor/api/graphql/query/user.js`
> > 
> > 
> > Perfect, wrap all the paths for resolvers, mutations and directives too. Please do proper testing in windows environment.
> 
> windows terminal? I have a Linux one 😊. Any ideas how can I get windows terminal just for this task? I am not on windows :)

dual boot windows or test on windows azure.

**Comment by jugshaurya** [comment]
@hereisnaman, OK will try on Window azure or on brothers laptop. will submit a PR soon.

**Comment by joeedwin** [comment]
@jugshaurya if you want i can test it bro

**Comment by jugshaurya** [comment]
@joeedwin, I have no problem, ask @hereisnaman him.

**Comment by 0xnmn** [comment]
@jugshaurya @joeedwin collaborating always helps in learning. Go ahead. I'll distribute the bounties.

**Comment by jugshaurya** [comment]
> @jugshaurya @joeedwin collaborating always helps in learning. Go ahead. I'll distribute the bounties.

@joeedwin, I will make changes soon.

**Comment by jugshaurya** [comment]
@hereisnaman, since all the  

> wrap all the paths for resolvers, mutations and directives too. Please do proper testing in windows environment.

@hereisnaman since all the generated files will have \u problems and it differs from machine to machine, user to user. Where should i use String.raw()? Can you tell me where these files are generated from ?

![a](https://user-images.githubusercontent.com/39825643/82286805-3cbad500-99bc-11ea-9337-5303d617dc5f.png)

**Comment by 0xnmn** [comment]
> @hereisnaman, since all the
> 
> > wrap all the paths for resolvers, mutations and directives too. Please do proper testing in windows environment.
> 
> @hereisnaman since all the generated files will have \u problems and it differs from machine to machine, user to user. Where should i use String.raw()? Can you tell me where these files are generated from ?
> 
> ![a](https://user-images.githubusercontent.com/39825643/82286805-3cbad500-99bc-11ea-9337-5303d617dc5f.png)

Study api/bin/generate.schema.js

**Comment by jugshaurya** [comment]
@hereisnaman, my solution is:- What do you think about this?
![hack](https://user-images.githubusercontent.com/39825643/82299221-e016e480-99d2-11ea-9c1c-545bfccddaa7.png)


File changed - api/bin/utils.js

**Comment by 0xnmn** [comment]
@jugshaurya looks fine, get it tested.

**Comment by jugshaurya** [comment]
@joeedwin any idea how are we going to do this collaboration?

**Comment by jugshaurya** [comment]
@hereisnaman should I create a PR to @joeedwin repo by adding him into my remote? and then he merges my changes are then he creates a PR to coding-blocks/gondor?

**Comment by joeedwin** [comment]
bro commit into your branch jugshaurya/gondor.
i will tell if it works then you pull request with  coding-blicks branch@jugshaurya

**Comment by joeedwin** [comment]
It works for me.@jugshaurya

**Comment by jugshaurya** [comment]
@hereisnaman verified by @joeedwin
