### ISSUE TITLE
[CalendarEventInvite] Fix N+1 issue in invites availability field

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#7]
To improve the performance of the query by reducing the no. of separate db queries. Need to batch the availability status check queries in [invite.availability](https://github.com/coding-blocks/gondor/blob/master/api/graphql/query/CalendarEventInvite/availability.js). 

Problem: [N+1](https://engineering.shopify.com/blogs/engineering/solving-the-n-1-problem-for-graphql-through-batching)
Solution: [Dataloader](https://www.npmjs.com/package/dataloader)
Learn: https://www.youtube.com/watch?v=OQTnXNCDywA

**Comment by joeedwin** [comment]
Can i work on this @hereisnaman

**Comment by kunal202** [comment]
Working on this!!

**Comment by joeedwin** [comment]
ok bro have you setup the code?
it is showing 404 for me
help me

**Comment by kunal202** [comment]
> ok bro have you setup the code?
> it is showing 404 for me
> help me

fork -> clone -> npm install -> npm install -g yarn -> yarn install -> yarn dev
Worked for me

**Comment by 0xnmn** [comment]
@joeedwin I am assigning it to you. Please share you ideas around solving this in the thread for discussing.

Let me know where I can help you.

**Comment by 0xnmn** [comment]
@prabalsingh24 what is the status on the fix?

**Comment by prabalsingh24** [comment]
> @prabalsingh24 what is the status on the fix?

I'll make another PR today to fix this. :) Sorry I was busy yesterday

**Comment by 0xnmn** [comment]
> > @prabalsingh24 what is the status on the fix?
> 
> I'll make another PR today to fix this. :) Sorry I was busy yesterday

no worries. Let me know if you need any help.
